/************************************************************\
 **     Copyright (c) 2012-2023 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/project/AnlogicFPGA/EG4S20/sd_isp_hdmi/td56/al_ip/BUFG.v
 ** Date	:	2024 04 29
 ** TD version	:	5.6.88061
\************************************************************/

`timescale 1ns / 1ps

module BUFG ( i, o );
		output 		o;
		input  		i;

		EG_LOGIC_BUFG bufg(
		.i(i),
		.o(o));

endmodule