--------------------------------------------------------------
 --     Copyright (c) 2012-2023 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	E:/project/AnlogicFPGA/EG4S20/sd_isp_hdmi/td56/al_ip/BUFG.vhd
 -- Date	:	2024 04 29
 -- TD version	:	5.6.88061
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY BUFG IS
PORT (
	i	: IN STD_LOGIC;
	o	: OUT STD_LOGIC
	);
END BUFG;

ARCHITECTURE struct OF BUFG IS

	BEGIN
	bufg : EG_LOGIC_BUFG
		PORT MAP (
			i	=> i,
			o	=> o
		);

END struct;
