--------------------------------------------------------------
 --     Copyright (c) 2012-2023 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	E:/Documents/2024/sd_isp_hdmi/td56/al_ip/crc7_bram.vhd
 -- Date	:	2024 04 05
 -- TD version	:	5.6.71036
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY eagle_macro;
	USE eagle_macro.EAGLE_COMPONENTS.all;

ENTITY crc7_bram IS
PORT (
	doa	: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);

	dia	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	addra	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	wea	: IN STD_LOGIC;
	clka	: IN STD_LOGIC
	);
END crc7_bram;

ARCHITECTURE struct OF crc7_bram IS

	BEGIN
	inst : EG_LOGIC_BRAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 8,
			ADDR_WIDTH_A	=> 8,
			DATA_DEPTH_A	=> 256,
			DATA_WIDTH_B	=> 8,
			ADDR_WIDTH_B	=> 8,
			DATA_DEPTH_B	=> 256,
			MODE			=> "SP",
			REGMODE_A	=> "NOREG",
			WRITEMODE_A	=> "NORMAL",
			RESETMODE	=> "SYNC",
			IMPLEMENT	=> "9K",
			DEBUGGABLE	=> "NO",
			PACKABLE		=> "NO",
			INIT_FILE	=> "../../rtl/sdcard_top/crc7_table.mif",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia	=> dia,
			dib	=> (others=>'0'),
			addra	=> addra,
			addrb	=> (others=>'0'),
			cea	=> '1',
			ceb	=> '0',
			clka	=> clka,
			clkb	=> '0',
			wea	=> wea,
			bea	=> (others=>'0'),
			beb	=> (others=>'0'),
			web	=> '0',
			rsta	=> '0',
			rstb	=> '0',
			doa	=> doa,
			dob	=> OPEN,
			ocea	=> '0',
			oceb	=> '0'
		);

END struct;
