/************************************************************\
 **     Copyright (c) 2012-2023 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/project/AnlogicFPGA/EG4S20/sd_isp_hdmi/td56/al_ip/pll_gen.v
 ** Date	:	2024 04 29
 ** TD version	:	5.6.88061
\************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:               50.000000MHz
//	Clock multiplication factor: 10
//	Clock division factor:       3
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C0        	| 166.666667MHZ	| 0.0000  DEG  
//		C1        	| 166.666667MHZ	| 270.0000 DEG  
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module pll_gen (
  refclk,
  reset,
  extlock,
  clk0_out,
  clk1_out 
);

  input refclk;
  input reset;
  output extlock;
  output clk0_out;
  output clk1_out;

  wire clk0_buf;

  EG_LOGIC_BUFG bufg_feedback (
    .i(clk0_buf),
    .o(clk0_out) 
  );

  EG_PHY_PLL #(
    .DPHASE_SOURCE("DISABLE"),
    .DYNCFG("DISABLE"),
    .FIN("50.000000"),
    .FEEDBK_MODE("NORMAL"),
    .FEEDBK_PATH("CLKC0_EXT"),
    .STDBY_ENABLE("DISABLE"),
    .PLLRST_ENA("ENABLE"),
    .SYNC_ENABLE("DISABLE"),
    .GMC_GAIN(0),
    .ICP_CURRENT(24),
    .KVCO(2),
    .LPF_CAPACITOR(2),
    .LPF_RESISTOR(4),
    .REFCLK_DIV(3),
    .FBCLK_DIV(10),
    .CLKC0_ENABLE("ENABLE"),
    .CLKC0_DIV(6),
    .CLKC0_CPHASE(5),
    .CLKC0_FPHASE(0),
    .CLKC1_ENABLE("ENABLE"),
    .CLKC1_DIV(6),
    .CLKC1_CPHASE(3),
    .CLKC1_FPHASE(4) 
  ) pll_inst (
    .refclk(refclk),
    .reset(reset),
    .stdby(1'b0),
    .extlock(extlock),
    .load_reg(1'b0),
    .psclk(1'b0),
    .psdown(1'b0),
    .psstep(1'b0),
    .psclksel(3'b000),
    .psdone(open),
    .dclk(1'b0),
    .dcs(1'b0),
    .dwe(1'b0),
    .di(8'b00000000),
    .daddr(6'b000000),
    .do({open, open, open, open, open, open, open, open}),
    .fbclk(clk0_out),
    .clkc({open, open, open, clk1_out, clk0_buf}) 
  );

endmodule

