/************************************************************\
 **     Copyright (c) 2012-2023 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/project/AnlogicFPGA/EG4S20/sd_isp_hdmi/td56/al_ip/tx_pll.v
 ** Date	:	2024 05 03
 ** TD version	:	5.6.88061
\************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:               50.000000Mhz
//	Clock multiplication factor: 3
//	Clock division factor:       2
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C1        	| 75.000000 MHZ	| 0.0000  DEG  
//		C2        	| 375.000000MHZ	| 0.0000  DEG  
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

module tx_pll (
  refclk,
  reset,
  extlock,
  clk1_out,
  clk2_out 
);

  input refclk;
  input reset;
  output extlock;
  output clk1_out;
  output clk2_out;

  wire clk1_buf;

  EG_LOGIC_BUFG bufg_feedback (
    .i(clk1_buf),
    .o(clk1_out) 
  );

  EG_PHY_PLL #(
    .DPHASE_SOURCE("DISABLE"),
    .DYNCFG("DISABLE"),
    .FIN("50.000000"),
    .FEEDBK_MODE("NORMAL"),
    .FEEDBK_PATH("CLKC1_EXT"),
    .STDBY_ENABLE("DISABLE"),
    .PLLRST_ENA("ENABLE"),
    .SYNC_ENABLE("DISABLE"),
    .GMC_GAIN(2),
    .ICP_CURRENT(24),
    .KVCO(2),
    .LPF_CAPACITOR(1),
    .LPF_RESISTOR(4),
    .REFCLK_DIV(2),
    .FBCLK_DIV(3),
    .CLKC1_ENABLE("ENABLE"),
    .CLKC1_DIV(15),
    .CLKC1_CPHASE(14),
    .CLKC1_FPHASE(0),
    .CLKC2_ENABLE("ENABLE"),
    .CLKC2_DIV(3),
    .CLKC2_CPHASE(2),
    .CLKC2_FPHASE(0) 
  ) pll_inst (
    .refclk(refclk),
    .reset(reset),
    .stdby(1'b0),
    .extlock(extlock),
    .load_reg(1'b0),
    .psclk(1'b0),
    .psdown(1'b0),
    .psstep(1'b0),
    .psclksel(3'b000),
    .psdone(open),
    .dclk(1'b0),
    .dcs(1'b0),
    .dwe(1'b0),
    .di(8'b00000000),
    .daddr(6'b000000),
    .do({open, open, open, open, open, open, open, open}),
    .fbclk(clk1_out),
    .clkc({open, open, clk2_out, clk1_buf, open}) 
  );

endmodule

